mydjango/apps/main/urls.py
from django.conf.urls import patterns, url

from .views import \
    MainPageView, AboutPageView


urlpatterns = patterns(
    '',
    url(r'^$', MainPageView.as_view(),
        name='index'),
    url(r'about/?$', AboutPageView.as_view(),
        name='about'),
)

mydjango/apps/mymodel/urls.py
# Create your views here.


from django.conf.urls import patterns, url

from .views import \
    (MyModelCreateView, MyModelUpdateView,
    MyModelDetailView, MyModelListView, MyModelDeleteView)


urlpatterns = patterns(
    '',
    url(r'create$',
        MyModelCreateView.as_view(),
        name='create'),
    url(r'edit/(?P<pk>\d+)/$',
        MyModelUpdateView.as_view(),
        name='update'),
    url(r'(?P<pk>\d+)/$',
        MyModelDetailView.as_view(),
        name='detail'),
    url(r'$',
        MyModelListView.as_view(),
        name='list'),
    url(r'delete/(?P<pk>\d+)/$',
        MyModelDeleteView.as_view(),
        name='delete')
)

mydjango/mydjango/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mydjango_project.views.home', name='home'),
    # url(r'^mydjango_project/', include('mydjango_project.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # Your project url
    url(r'^', include('apps.main.urls',
                       namespace='main',
                       app_name='main')),
    url(r'^mymodel/', include('apps.mymodel.urls',
                              namespace='mymodel',
                              app_name='mymodel'))
)

mydjango/apps/core/models.py
from django.db import models

# Create your models here.


class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides
    self-updating 'created' and 'modified' fields.
    """
    created = models.DateTimeField(
        auto_now_add=True
    )
    modified = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        abstract = True

mydjango/apps/mymodel/models.py
from django.db import models
from django.utils.translation \
    import ugettext_lazy as _
from django.core.urlresolvers import \
    reverse

# Create your models here.
from ..core.models import TimeStampedModel


class MyModel(TimeStampedModel):
    """
    Just example of model
    """
    title = models.CharField(
        _('Title'),
        max_length=200
    )

    def get_absolute_url(self):
        return reverse('mymodel:detail',
                       args=[self.pk])

    def __unicode__(self):
        return self.title

mydjango/apps/mymodel/forms.py
from django import forms

from .models import MyModel


class MyModelForm(forms.ModelForm):
    class Meta:
        model = MyModel

mydjango/apps/core/views.py
# Create your views here.

mydjango/apps/main/views.py
from django.views.generic import TemplateView


class MainPageView(TemplateView):
    template_name = 'main/index.html'


class AboutPageView(TemplateView):
    template_name = 'main/about.html'

mydjango/apps/mymodel/views.py
from django.views.generic import \
    CreateView, DetailView, ListView, UpdateView, DeleteView

from .models import MyModel
from .forms import MyModelForm


class MyModelCreateView(CreateView):
    model = MyModel
    form_class = MyModelForm


class MyModelUpdateView(UpdateView):
    model = MyModel
    form_class = MyModelForm


class MyModelDetailView(DetailView):
    model = MyModel


class MyModelListView(ListView):
    model = MyModel


class MyModelDeleteView(DeleteView):
    model = MyModel

mydjango/templates/base.html
{% load static %}
<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width" />

  <title>MyApplication :: {% block title %}{% endblock %}</title>

  <!-- Included CSS Files (Uncompressed) -->
  <!--
  <link rel="stylesheet" href="stylesheets/foundation.css">
  -->

  <!-- Included CSS Files (Compressed) -->
  <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/app.css' %}">
  {% block extra_head %}{% endblock %}
  <script src="{% static 'js/modernizr.foundation.js' %}"></script>
</head>
<body>
  {% include 'navigation/top_nav.html' %}
  {% block content %}{% endblock %}

  <!-- Included JS Files (Uncompressed) -->
  <!--
  <script src="javascripts/jquery.js"></script><script src="javascripts/jquery.foundation.mediaQueryToggle.js"></script><script src="javascripts/jquery.foundation.forms.js"></script><script src="javascripts/jquery.foundation.reveal.js"></script><script src="javascripts/jquery.foundation.orbit.js"></script><script src="javascripts/jquery.foundation.navigation.js"></script><script src="javascripts/jquery.foundation.buttons.js"></script><script src="javascripts/jquery.foundation.tabs.js"></script><script src="javascripts/jquery.foundation.tooltips.js"></script><script src="javascripts/jquery.foundation.accordion.js"></script><script src="javascripts/jquery.placeholder.js"></script><script src="javascripts/jquery.foundation.alerts.js"></script><script src="javascripts/jquery.foundation.topbar.js"></script><script src="javascripts/jquery.foundation.joyride.js"></script><script src="javascripts/jquery.foundation.clearing.js"></script><script src="javascripts/jquery.foundation.magellan.js"></script>
  -->

  <!-- Included JS Files (Compressed) -->
  <script src="{% static 'js/jquery.js' %}"></script>
  <script src="{% static 'js/foundation.min.js' %}"></script>

  <!-- Initialize JS Plugins -->
  <script src="{% static 'js/app.js' %}"></script>


    <script>
    $(window).load(function(){
      $("#featured").orbit();
    });
    </script>

</body>
</html>

mydjango/templates/main/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock %}
{% block content %}
<h1>About my application</h1>
{% endblock %}

mydjango/templates/main/index.html
{% extends 'base.html' %}
{% block title %}Main page{% endblock %}
{% block content %}
  <div class="row">
    <div class="twelve columns">
      <h2>Welcome to My Application</h2>
      <p>This is version <strong>3.2.5</strong> generated on January 26, 2013.</p>
      <hr />
    </div>
  </div>

  <div class="row">
    <div class="eight columns">
      <h3>The Grid</h3>

      <!-- Grid Example -->
      <div class="row">
        <div class="twelve columns">
          <div class="panel">
            <p>This is a twelve column section in a row. Each of these includes a div.panel element so you can see where the columns are - it's not required at all for the grid.</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="six columns">
          <div class="panel">
            <p>Six columns</p>
          </div>
        </div>
        <div class="six columns">
          <div class="panel">
            <p>Six columns</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="four columns">
          <div class="panel">
            <p>Four columns</p>
          </div>
        </div>
        <div class="four columns">
          <div class="panel">
            <p>Four columns</p>
          </div>
        </div>
        <div class="four columns">
          <div class="panel">
            <p>Four columns</p>
          </div>
        </div>
      </div>


      <h3>Tabs</h3>
      <dl class="tabs">
        <dd class="active"><a href="#simple1">Simple Tab 1</a></dd>
        <dd><a href="#simple2">Simple Tab 2</a></dd>
        <dd><a href="#simple3">Simple Tab 3</a></dd>
      </dl>

      <ul class="tabs-content">
        <li class="active" id="simple1Tab">This is simple tab 1's content. Pretty neat, huh?</li>
        <li id="simple2Tab">This is simple tab 2's content. Now you see it!</li>
        <li id="simple3Tab">This is simple tab 3's content. It's, you know...okay.</li>
      </ul>



      <h3>Buttons</h3>

      <div class="row">
        <div class="six columns">
          <p><a href="#" class="small button">Small Button</a></p>
          <p><a href="#" class="button">Medium Button</a></p>
          <p><a href="#" class="large button">Large Button</a></p>
        </div>
        <div class="six columns">
          <p><a href="#" class="small alert button">Small Alert Button</a></p>
          <p><a href="#" class="success button">Medium Success Button</a></p>
          <p><a href="#" class="large secondary button">Large Secondary Button</a></p>
        </div>
      </div>

    </div>

    <div class="four columns">
      <h4>Getting Started</h4>
      <p>We're stoked you want to try Foundation! To get going, this file (index.html) includes some basic styles you can modify, play around with, or totally destroy to get going.</p>

      <h4>Other Resources</h4>
      <p>Once you've exhausted the fun in this document, you should check out:</p>
      <ul class="disc">
        <li><a href="http://foundation.zurb.com/docs">Foundation Documentation</a><br />Everything you need to know about using the framework.</li>
        <li><a href="http://github.com/zurb/foundation">Foundation on Github</a><br />Latest code, issue reports, feature requests and more.</li>
        <li><a href="http://twitter.com/foundationzurb">@foundationzurb</a><br />Ping us on Twitter if you have questions. If you build something with this we'd love to see it (and send you a totally boss sticker).</li>
      </ul>
    </div>
  </div>


  <div class="row">
    <div class="twelve columns">
      <h3>Orbit</h3>
      <div id="featured">
        <img src="holder.js/1200x250/text:Slide_1" alt="slide image">
        <img src="holder.js/1200x250/text:Slide_2" alt="slide image">
        <img src="holder.js/1200x250/text:Slide_3" alt="slide image">
      </div>
    </div>
  </div>



  <div class="row">
    <div class="twelve columns">
      <h3>Reveal</h3>
      <p><a href="#" data-reveal-id="exampleModal" class="button">Example modal</a></p>
    </div>
  </div>

  <div id="exampleModal" class="reveal-modal">
    <h2>This is a modal.</h2>
    <p>
      Reveal makes these very easy to summon and dismiss. The close button is simple an anchor with a unicode
      character icon and a class of <code>close-reveal-modal</code>. Clicking anywhere outside the modal will
      also dismiss it.
    </p>
    <a class="close-reveal-modal">×</a>
  </div>


{% endblock %}

mydjango/templates/mymodel/mymodel_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'Confirm delete' %} {{ object }}{% endblock %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

mydjango/templates/mymodel/mymodel_detail.html
{% extends 'base.html' %}
{% block title %}{{ object }}{% endblock %}
{% block content %}
<a href="{% url 'mymodel:update' object.id%}">
    Edit
</a>
<h1>{{ object }}</h1>
<h2>{{ object.created }}</h2>
{% endblock %}

mydjango/templates/mymodel/mymodel_form.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}
    {% if object %}
        {% trans 'Edit' %} {{ object.title }}
    {% else %}
        {% trans 'Create' %}
    {% endif %}
{% endblock %}
{% block content %}
<h1>{% if object %}{{ object.title }}{% else %}{% trans 'Create' %}{% endif %}</h1>
<form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="{% trans 'Submit' %}" />
</form>
{% endblock %}

mydjango/templates/mymodel/mymodel_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'List of my model'%}{% endblock %}
{% block content %}
<h1>{% trans 'List of my model' %}</h1>
<table>
  <thead>
    <tr>
      <th width="200">{% trans 'ID' %}</th>
      <th>{% trans 'Title' %}</th>
      <th width="150">{% trans 'Created' %}</th>
      <th width="150">{% trans 'Modified' %}</th>
    </tr>
  </thead>
  <tbody>
  {% for object in object_list %}
    <tr>
      <td><a href="{% url 'mymodel:detail' object.id %}">
        {{ object.title }}</a></td>
      <td>{{ object.created }}</td>
      <td>{{ object.modified }}</td>
    </tr>
  {% empty %}
      <tr>
        <td colspan="3">
            {% trans 'No objects yet' %}
        </td>
      </tr>
  {% endfor %}
  </tbody>
</table>
{% endblock %}

mydjango/templates/navigation/top_nav.html
{% load i18n %}
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><a href="{% url 'main:index' %}">{% trans 'My web app' %}</a></h1>
    </li>
    <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon">
        <a href="#"><span>{% trans 'Menu' %}</span></a></li>
    <ul class="left">
      <li class="divider"></li>
      {% url 'mymodel:list' as list_url %}
      <li class="has-dropdown {% ifequal request.path list_url %}active{% endifequal %}"><a href="#">MyModels</a>
        <ul class="dropdown">
          <li><a href="{% url 'mymodel:create' %}">Create</a></li>
          <li><a href="{{ list_url }}">See all&rarr;</a></li>
        </ul>
      </li>
      <li class="divider"></li>
      {% url 'main:about' as about_url %}
      <li {% ifequal request.path about_url %}class="active"{% endifequal %}><a href="{{ about_url }}">{% trans 'About' %}</a></li>
      <li class="divider"></li>
    </ul>
  </ul>
</nav>